/* The following code was generated by JFlex 1.6.1 */

package analisador;

import static analisador.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
*/
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\6\1\53\1\53\1\6\22\0\1\5\1\46\1\51"+
    "\1\52\1\3\1\41\1\42\1\0\1\47\1\50\1\40\1\36\1\51"+
    "\1\37\1\51\1\41\12\2\1\0\1\51\1\44\1\45\1\44\1\0"+
    "\1\4\32\1\1\51\1\0\1\51\1\0\1\1\1\0\1\13\1\17"+
    "\1\21\1\25\1\15\1\26\1\30\1\34\1\11\1\1\1\31\1\20"+
    "\1\27\1\24\1\32\1\7\1\1\1\10\1\22\1\14\1\16\1\12"+
    "\1\35\1\23\1\33\1\1\1\51\1\43\1\51\7\0\1\53\u1fa2\0"+
    "\1\53\1\53\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\5\21\2"+
    "\4\6\2\1\1\7\1\10\1\1\2\11\1\12\1\13"+
    "\1\14\1\0\3\2\1\15\30\2\1\10\1\6\1\16"+
    "\1\7\1\0\1\17\25\2\1\15\5\2\1\0\7\2"+
    "\1\20\4\2\1\3\10\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\54\0\54"+
    "\0\u0108\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c"+
    "\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c"+
    "\0\u03c8\0\u03f4\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\u04fc"+
    "\0\u04fc\0\u04fc\0\u0528\0\54\0\54\0\u0554\0\u0580\0\u05ac"+
    "\0\u05d8\0\u0604\0\u0630\0\130\0\u065c\0\u0688\0\u06b4\0\u06e0"+
    "\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840"+
    "\0\u086c\0\u0898\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\u09a0"+
    "\0\u09cc\0\u09f8\0\u0a24\0\u0a50\0\54\0\54\0\54\0\54"+
    "\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0"+
    "\0\u0bdc\0\u0c08\0\u0c34\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10"+
    "\0\u0d3c\0\u0d68\0\u0d94\0\u0dc0\0\u0dec\0\u0e18\0\u0e44\0\u0e70"+
    "\0\u0e9c\0\u0ec8\0\u0ef4\0\u0f20\0\u0f4c\0\u0f78\0\u0fa4\0\u0fd0"+
    "\0\u0ffc\0\u1028\0\u1054\0\u1080\0\u10ac\0\130\0\u10d8\0\u1104"+
    "\0\u1130\0\u115c\0\54\0\u1188\0\u11b4\0\u11e0\0\u120c\0\u1238"+
    "\0\u1264\0\u1290\0\u12bc";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\3\1\14\1\15\1\16\1\17\1\20"+
    "\1\3\1\21\1\22\1\3\1\23\1\24\1\25\1\26"+
    "\2\3\1\27\1\30\1\3\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\2\44"+
    "\1\45\56\0\2\3\4\0\27\3\20\0\1\4\52\0"+
    "\1\46\5\0\27\46\17\0\1\47\2\0\1\50\2\0"+
    "\27\47\17\0\2\3\4\0\1\3\1\51\5\3\1\52"+
    "\17\3\17\0\2\3\4\0\6\3\1\53\20\3\17\0"+
    "\2\3\4\0\15\3\1\54\1\3\1\54\1\55\6\3"+
    "\17\0\2\3\4\0\11\3\1\56\3\3\1\57\11\3"+
    "\17\0\2\3\4\0\1\3\1\60\23\3\1\61\1\3"+
    "\17\0\2\3\4\0\11\3\1\62\2\3\1\63\1\64"+
    "\11\3\17\0\2\3\4\0\15\3\1\65\11\3\17\0"+
    "\2\3\4\0\1\3\1\66\4\3\1\67\20\3\17\0"+
    "\2\3\4\0\4\3\1\70\4\3\1\71\15\3\17\0"+
    "\2\3\4\0\6\3\1\72\1\73\17\3\17\0\2\3"+
    "\4\0\2\3\1\74\3\3\1\75\14\3\1\76\3\3"+
    "\17\0\2\3\4\0\6\3\1\77\14\3\1\54\3\3"+
    "\17\0\2\3\4\0\2\3\1\100\1\3\1\101\16\3"+
    "\1\27\3\3\17\0\2\3\4\0\23\3\1\102\3\3"+
    "\17\0\2\3\4\0\1\3\1\54\25\3\17\0\2\3"+
    "\4\0\2\3\1\103\24\3\17\0\2\3\4\0\25\3"+
    "\1\104\1\3\54\0\1\105\6\0\1\105\45\0\1\105"+
    "\5\0\1\105\46\0\1\106\4\0\1\105\53\0\1\105"+
    "\50\0\1\107\54\0\1\107\55\0\1\110\45\0\1\111"+
    "\15\0\2\46\4\0\27\46\17\0\2\47\4\0\27\47"+
    "\17\0\1\112\5\0\27\112\17\0\2\3\4\0\2\3"+
    "\1\113\24\3\17\0\2\3\4\0\10\3\1\114\16\3"+
    "\17\0\2\3\4\0\5\3\1\115\5\3\1\116\2\3"+
    "\1\117\10\3\17\0\2\3\4\0\1\120\26\3\17\0"+
    "\2\3\4\0\2\3\1\121\24\3\17\0\2\3\4\0"+
    "\16\3\1\54\10\3\17\0\2\3\4\0\7\3\1\122"+
    "\17\3\17\0\2\3\4\0\6\3\1\123\20\3\17\0"+
    "\2\3\4\0\13\3\1\124\13\3\17\0\2\3\4\0"+
    "\5\3\1\125\21\3\17\0\2\3\4\0\13\3\1\126"+
    "\2\3\1\54\10\3\17\0\2\3\4\0\5\3\1\127"+
    "\3\3\1\130\4\3\1\131\10\3\17\0\2\3\4\0"+
    "\6\3\1\132\20\3\17\0\2\3\4\0\21\3\1\133"+
    "\5\3\17\0\2\3\4\0\13\3\1\134\13\3\17\0"+
    "\2\3\4\0\4\3\1\135\22\3\17\0\2\3\4\0"+
    "\11\3\1\136\15\3\17\0\2\3\4\0\1\137\26\3"+
    "\17\0\2\3\4\0\11\3\1\54\15\3\17\0\2\3"+
    "\4\0\14\3\1\76\12\3\17\0\2\3\4\0\5\3"+
    "\1\54\21\3\17\0\2\3\4\0\17\3\1\140\7\3"+
    "\17\0\2\3\4\0\15\3\1\141\11\3\17\0\2\3"+
    "\4\0\11\3\1\142\15\3\17\0\2\3\4\0\16\3"+
    "\1\143\10\3\17\0\2\3\4\0\6\3\1\144\20\3"+
    "\17\0\2\3\4\0\2\3\1\145\3\3\1\123\20\3"+
    "\20\0\1\146\52\0\2\112\4\0\27\112\17\0\2\3"+
    "\4\0\3\3\1\147\23\3\17\0\2\3\4\0\11\3"+
    "\1\150\15\3\17\0\2\3\4\0\1\3\1\151\5\3"+
    "\1\152\17\3\17\0\2\3\4\0\12\3\1\153\14\3"+
    "\17\0\2\3\4\0\23\3\1\54\3\3\17\0\2\3"+
    "\4\0\11\3\1\154\15\3\17\0\2\3\4\0\4\3"+
    "\1\155\22\3\17\0\2\3\4\0\6\3\1\156\20\3"+
    "\17\0\2\3\4\0\15\3\1\54\11\3\17\0\2\3"+
    "\4\0\2\3\1\136\3\3\1\54\20\3\17\0\2\3"+
    "\4\0\6\3\1\157\20\3\17\0\2\3\4\0\7\3"+
    "\1\160\17\3\17\0\2\3\4\0\2\3\1\74\24\3"+
    "\17\0\2\3\4\0\6\3\1\135\20\3\17\0\2\3"+
    "\4\0\6\3\1\72\20\3\17\0\2\3\4\0\4\3"+
    "\1\161\22\3\17\0\2\3\4\0\2\3\1\123\24\3"+
    "\17\0\2\3\4\0\6\3\1\54\20\3\17\0\2\3"+
    "\4\0\13\3\1\155\13\3\17\0\2\3\4\0\17\3"+
    "\1\54\7\3\17\0\2\3\4\0\6\3\1\27\20\3"+
    "\17\0\2\3\4\0\2\3\1\162\24\3\17\0\2\3"+
    "\4\0\4\3\1\74\22\3\17\0\2\3\4\0\13\3"+
    "\1\122\13\3\17\0\2\3\4\0\7\3\1\145\17\3"+
    "\17\0\2\3\4\0\11\3\1\57\15\3\17\0\2\3"+
    "\4\0\11\3\1\134\15\3\20\0\1\146\45\0\1\163"+
    "\4\0\2\3\4\0\4\3\1\164\22\3\17\0\2\3"+
    "\4\0\2\3\1\165\24\3\17\0\2\3\4\0\24\3"+
    "\1\54\2\3\17\0\2\3\4\0\1\3\1\123\25\3"+
    "\17\0\2\3\4\0\7\3\1\134\17\3\17\0\2\3"+
    "\4\0\6\3\1\166\20\3\17\0\2\3\4\0\13\3"+
    "\1\54\13\3\17\0\2\3\4\0\15\3\1\167\11\3"+
    "\17\0\2\3\4\0\1\3\1\134\25\3\17\0\2\3"+
    "\4\0\22\3\1\54\4\3\17\0\2\3\4\0\15\3"+
    "\1\170\11\3\17\0\2\3\4\0\5\3\1\134\21\3"+
    "\17\0\2\3\4\0\12\3\1\54\14\3\17\0\2\3"+
    "\4\0\20\3\1\171\6\3\17\0\2\3\4\0\16\3"+
    "\1\155\10\3\17\0\2\3\4\0\6\3\1\57\20\3"+
    "\17\0\2\3\4\0\6\3\1\172\20\3\17\0\2\3"+
    "\4\0\15\3\1\173\11\3\17\0\2\3\4\0\5\3"+
    "\1\155\21\3\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4840];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\2\11\33\1\2\11\2\1\1\0"+
    "\34\1\4\11\1\0\34\1\1\0\14\1\1\11\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return ERROR;
            }
          case 17: break;
          case 2: 
            { lexeme=yytext(); return ID;
            }
          case 18: break;
          case 3: 
            { lexeme=yytext(); return NUMERO;
            }
          case 19: break;
          case 4: 
            { /*Ignore*/
            }
          case 20: break;
          case 5: 
            { lexeme = yytext(); return QUEBRA_LINHA;
            }
          case 21: break;
          case 6: 
            { lexeme = yytext(); return OPERADOR_ARITMETICO;
            }
          case 22: break;
          case 7: 
            { lexeme = yytext(); return OP_RELACIONAL;
            }
          case 23: break;
          case 8: 
            { lexeme = yytext(); return OP_ATRIBUICAO;
            }
          case 24: break;
          case 9: 
            { lexeme = yytext(); return SEPARADOR;
            }
          case 25: break;
          case 10: 
            { lexeme = yytext(); return COMENTARIO;
            }
          case 26: break;
          case 11: 
            { lexeme=yytext(); return VARIAVEL;
            }
          case 27: break;
          case 12: 
            { lexeme=yytext(); return VARIAVEL_INSTANCIA;
            }
          case 28: break;
          case 13: 
            { lexeme = yytext(); return PALAVRA;
            }
          case 29: break;
          case 14: 
            { lexeme = yytext(); return OPERADOR_LOGICO;
            }
          case 30: break;
          case 15: 
            { lexeme=yytext(); return VARIAVEL_CLASSE;
            }
          case 31: break;
          case 16: 
            { lexeme=yytext(); return OP_BOOLEANO;
            }
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
