
package analisador;


public enum Token {
    PALAVRA,OPERADOR_ARITMETICO, OPERADOR_LOGICO,OP_ATRIBUICAO, OP_RELACIONAL, OP_BOOLEANO, SEPARADOR,
    ESPECIAL, COMENTARIO, ID, INT,NUMERO, ERROR, VARIAVEL, VARIAVEL_INSTANCIA, VARIAVEL_CLASSE, QUEBRA_LINHA
}
